### ISSUE TITLE
API LUA Error

### ISSUE THREAD

**Issue by WarCrewPT** [shagu/pfUI#1042]
Hello

I wanted to install this addon on to classic however I have been constantly prompted in chat with an error message. See below.

![Untitled](https://user-images.githubusercontent.com/45229409/130327708-32055418-f140-4510-be8a-faa05a3dad3f.png)

I am not able to use /pfui on to chat. Also, I have deleted all my addons to make sure it wasn't any conflict with my other addons.

**Comment by shagu** [comment]
> An AddOn for World of Warcraft: Vanilla (1.12.1) and The Burning Crusade (2.4.3) [...]

> Will there be pfUI for Activision's "Classic" remakes?
No, it would require an entire rewrite of the AddOn since the game is now a different one. The AddOn-API has evolved during the last 15 years and the new "Classic" versions are based on a current retail gameclient. I don't plan to play any of those new versions, so I won't be porting any of my addons to it.

Please read the readme.
