### ISSUE TITLE
tbc version not working at current version 2.5.2.40892

### ISSUE THREAD

**Issue by Shuraken007** [shagu/pfUI#1052]
![image](https://user-images.githubusercontent.com/23379636/140619715-066143e5-235c-4298-8265-21df931cf07c.png)

Hello, tried your addon at burning crusade classic, got this errors.
Load it with this link, use name pfUI-tbc
https://github.com/shagu/pfUI/archive/master.zip

**Comment by shagu** [comment]
Hello,

The addon is build for the original 1.12.1 game client from 2006 and the 2.4.3 one from 2007. 
It won't get updated to any of the current retail versions.

For further details, here's a quote from the [FAQ](https://github.com/shagu/pfUI):

> Will there be pfUI for Activision's "Classic" remakes?
No, it would require an entire rewrite of the AddOn since the game is now a different one. The AddOn-API has evolved during the last 15 years and the new "Classic" versions are based on a current retail gameclient. I don't plan to play any of those new versions, so I won't be porting any of my addons to it.

**Comment by Shuraken007** [comment]
oh, sorry - it was a bit silly posting then
yeah, it would took lot of time, there are better things to spend time on
