### ISSUE TITLE
Font request

### ISSUE THREAD

**Issue by Sagenod** [shagu/pfUI#1067]
Can you please add Jacinto font to the pfUI-fonts package, or give me some insight as to how to make it work?  I tried to include it by adding it to font list and including a new line in the pfUI-fonts.lua, but when selected in the pfUI game config. the font does not function.

It would be awesome if you could add it to the font list, would greatly appreciate it
[jacinto_sans.zip](https://github.com/shagu/pfUI/files/8714596/jacinto_sans.zip)

**Comment by shagu** [comment]
Due to the license I will not add the font to pfUI or the pfUI-fonts addons.
To add it yourself, place the *.ttf file into the `fonts` folder of pfUI-fonts and add the name to the pfUI-fonts.lua.
Make sure to restart the game afterwards, otherwise it won't pick up new files.
For further questions about pfUI-fonts, please use the pfUI-fonts issue tracker.
