### ISSUE TITLE
Reputaiton bar always shows "XP" when set to "automatic"

### ISSUE THREAD

**Issue by fairtale5** [shagu/pfUI#1117]
The right XP bar, when set to [Display Mode: Automatic], always displays XP (the same as the left bar).

The behavior I was expecting would be that it displays OTHER info then the left bar. For example, latest reputation gains. I know there is a setting for "last reputation", but then it would not be automatic (for example, hunter pet XP etc).

Could the "automatic" be changed to never show the same as the left bar to avoid duplicated data?

**Comment by shagu** [comment]
No, not really. "Automatic" will show XP as long as XP exists (until max level) and then swaps to Reputation.
It's mainly there for people who only want one bar and don't care much about their rep grind on early levels.

Changing behaviour of a setting is something I won't do because it would break the settings for people who update.
Feel free to send a PR with a new option that auto-toggles between PetXP and Rep if thats what you want.
