### ISSUE TITLE
不显示 NPC姓名了

### ISSUE THREAD

**Issue by tjjxlbj** [shagu/pfUI#1119]
最近版本不显示 NPC姓名了。

**Comment by shagu** [comment]
Pretty sure this is unrelated to pfUI. The game has a builtin option wether to shop NPC names or not.
Press "Escape" and open "Interface" settings.

**Comment by tjjxlbj** [comment]
> 很确定这与pfUI无关。该游戏有一个内置选项，无论是否购买NPC名称。 按“逃生”并打开“界面”设置。

我禁用pfUI就能显示，之前的版本没问题，用新版本是不是需要删除原来版本pfUI的设置，

**Comment by shagu** [comment]
I was able to find the issue. It was introduced via: https://github.com/shagu/pfUI/pull/1105 and is now fixed with https://github.com/shagu/pfUI/commit/e6af9ea6bff161a366c36e8d3ac17d63778dca55

We forgot to set the region font of unit names in that change. 
If you update to the latest version pfUI, everything will work again :)
