### ISSUE TITLE
Ability

### ISSUE THREAD

**Issue by wexio** [shagu/pfUI#1214]
When i go in stealth with my rogue after leaving stealth, PFui stilltrying use abilities which areused in stealth like Ambush. I disabled addon and its ok after i Use PFui abilities wont workafter vanish .

**Comment by shagu** [comment]
Sounds like a configuration or another addon issue. You might want to try to disable all other addons to test again.
Also you could save your `WTF` folder and try again with a fresh one. Because Keybinds and ability triggers are done by the game, not by pfUI. I also never had that issue, neither on my druids nor on my rogues.
