### ISSUE TITLE
[Feature Request and Issue] Nameplate module

### ISSUE THREAD

**Issue by wangmeng2410** [shagu/pfUI#1218]
ENV: Turtle wow(EU) with latest PFUI

issue: Mobs will display the hostile player's class color

request: It's better to add the mobs' mana bar if they are magic ones

**Comment by shagu** [comment]
> issue: Mobs will display the hostile player's class color

Can't be done better. Because Nameplates cannot be checked for classes, if you seen a guy with the name of the mob, it would assume it is him, as the only way to detect player is, to scan their name and check the plate on it.

> request: It's better to add the mobs' mana bar if they are magic ones

Would only work on nameplates while you have them in target.


Sorry, but it's vanilla - There are no APIs for nameplates at all
