### ISSUE TITLE
librange: initial combo points lost due to client timing issues

### ISSUE THREAD

**Issue by pabonamu** [shagu/pfUI#1263]
I saw a fix what was made for the issue of missing combo points. I actually noticed this problem a few months ago, but I didn't report it at the time. Instead, I just switched to using a different UI addon. After seeing the fix was made, I downloaded the new pfUI to use. 
However, in recent raids, I still noticed instances of missing combo points. Unfortunately, I didn't record it, but it definitely happened. It usually occurs at the beginning of a boss fight and then doesn't happen again. I couldn't reproduce the issue in target dummy testing. I hope my feedback catches your attention and the issue gets fixed soon. pfUI is a great addon, I like it.

**Comment by Synven** [comment]
I can confirm the same issue. Raiding on a druid is not possible with current PFUI(feral cat). Sometimes it will generate combo points and others i get nothing for entire mobs.

**Comment by welpenhund** [comment]
I can confirm this too, and  the reason why it happens seems to have to do something with "click to cast" mouseover.
Maybe the developer can make a check that if a druid is in cat form, that the target swaps/mouseover clicktocast are not working. Only while out of form (not like we can heal or dispel in form anyways)
´That might fix getting our combo points removed while in cat.

**Comment by pabonamu** [comment]
![image](https://github.com/shagu/pfUI/assets/45550702/dbe78b1d-ea04-41d8-9398-b781a871c708)
This modification didn't completely solve this problem. I hope any developers can pay attention to it. I really wanna switch back to PFUI

**Comment by Sartigen** [comment]
I can also confirm this is the case as of last Saturday. It seems to have gotten better but not entirely resolved. This has been going on for over a month for me for sure. I started noticing it in aq40 raid.

**Comment by welpenhund** [comment]
bump @shagu

**Comment by shagu** [comment]
I can't help here, because I was never able to reproduce the issue on my druid.
I also don't see any other code within pfUI that would change the target.

The only automatic target-change that happens is inside the 40y range check emulation, which was already fixed by @gwetchen(https://github.com/shagu/pfUI/commit/d7a7387465038d3f1b6e3e411ed73fd0f1bdc3a5).

If there's still issues with that, please try to disable the 40y rangecheck and see if it got better.

The other target-switch that can happen is when using mouseover macros or focus-frame casts, but that's something which cannot be fixed in vanilla. Because It will always silently switch target to cast the spell and then switch back.

Also, are you sure it's not related to any other target-changing addons like HonorSpy, NPCScan, UnitScan, etc?

Please let me know if you find a way to reproduce with only pfUI and I'll gladly help to fix the issue.
But as of now, there's nothing I can do here.

**Comment by Sartigen** [comment]
hey @shagu , in my case this is a newish issue. I have been using PFUI for a while and it was fine. Only started bugging out a few months ago. So I'm thinking of doing the following to troubleshoot:

-clean install of turtlewow with no other addons other than PFUI

If that is successful, then I will reinstall the addons I currently have one at a time until it triggers the issue. 

If it doesnt fix it then perhaps you can help suggest things to disable such as the 40y range check. 

I'll also record my screen if it persists. This is a bit tricky to test since I can only replicate it in raids.

Any other suggestions that might be helpful to test?

thanks!

**Comment by Sartigen** [comment]
@shagu ill also try disabling the 40y check first and let you know.

**Comment by welpenhund** [comment]
> I can't help here, because I was never able to reproduce the issue on my druid. I also don't see any other code within pfUI that would change the target.
> 
> The only automatic target-change that happens is inside the 40y range check emulation, which was already fixed by @gwetchen([d7a7387](https://github.com/shagu/pfUI/commit/d7a7387465038d3f1b6e3e411ed73fd0f1bdc3a5)).
> 
> If there's still issues with that, please try to disable the 40y rangecheck and see if it gets better.
> 
> The other target-switch that can happen is when using mouseover macros or focus-frame casts, but that's something which cannot be fixed in vanilla. Because It will always silently switch target to cast the spell and then switch back.
> 
> Also, are you sure it's not related to any other target-changing addons like HonorSpy, NPCScan, UnitScan, etc?
> 
> Please let me know if you find a way to reproduce with only pfUI and I'll gladly help to fix the issue. But as of now, there's nothing I can do here.

Could you implement a check that the mouseover casting for raid frames is disabled as long as the druid is in cat or bear form? 
So that it only does apply the cast when form is removed? Dunno if that would help maybe? :)

**Comment by shagu** [comment]
> Could you implement a check that the mouseover casting for raid frames is disabled as long as the druid is in cat form? So that it only does apply the cast when form is removed? Dunno if that would help maybe? :)

No, there are way too many people that rely on the mouseover to quickly throw and innvervate, battlerez or heal.
Just don't cast something on others if you want to keep your combo points.

**Comment by shagu** [comment]
> Any other suggestions that might be helpful to test?

1. Without any other addons
2. With 40y rangecheck disabled
3. If you use /startattack macros [or ones that include AttackTarget()], try without them

I have no other ideas what could possibly switch targets or confuse the 40y range check.

**Comment by shagu** [comment]
Finally I found a way to reproduce it at the training dummies in orgrimmar. 
Here's how to lose the combopoints of the openening hit:

1. Move to Training Dummies
2. Group with a character and move him to like 35-40y away from you (>28y and <40y)
3. Enable the 40y Range Check in the pfUI settings
4. Set "Range Check Interval" to "Very Fast"
5. Clear your target and make sure to not have any Combo Points
6. Target the Training Dummy
7. Open the fight on the training dummy with a Combo Point generating hit like Claw

It's now visible how 1-2 combo points appear for a very short time and directly disappear again.
Like this I'm able to reproduce the loss of opener combo points at a rate of > 90%.

As it is nice to know a way to reproduce, it is also sad why it happens: 

After quite some time of debugging it turned out that both event checks (`InCombat` and `ComboPoints`) are only received with a delay from the server. That communication delay between server and client (or even just client internal?) is bigger than the interval of the range checks. Meaning that when the client detects one of the pause-events, the range check already continued scanning 1-2 units and therefore resetting the combo points back, before the client even notices that he had some.

Sadly, there's also no other usable event fired, that could be use to put in another delay, right after the opener is pressed. So the only way to fix it, would be to disable the 40y-range-check entirely while being in cat form. And therefore turning it back from 40y to the game default of 28y while in this form.

**Comment by welpenhund** [comment]
> Finally I found a way to reproduce it at the training dummies in orgrimmar. Here's how to lose the combopoints of the openening hit:
> 
>     1. Move to Training Dummies
> 
>     2. Group with a character and move him to like 35-40y away from you (>28y and <40y)
> 
>     3. Enable the 40y Range Check in the pfUI settings
> 
>     4. Set "Range Check Interval" to "Very Fast"
> 
>     5. Clear your target and make sure to not have any Combo Points
> 
>     6. Target the Training Dummy
> 
>     7. Open the fight on the training dummy with a Combo Point generating hit like Claw
> 
> 
> It's now visible how 1-2 combo points appear for a very short time and directly disappear again. Like this I'm able to reproduce the loss of opener combo points at a rate of > 90%.
> 
> As it is nice to know a way to reproduce, it is also sad why it happens:
> 
> After quite some time of debugging it turned out that both event checks (`InCombat` and `ComboPoints`) are only received with a delay from the server. That communication delay between server and client (or even just client internal?) is bigger than the interval of the range checks. Meaning that when the client detects one of the pause-events, the range check already continued scanning 1-2 units and therefore resetting the combo points back, before the client even notices that he had some.
> 
> Sadly, there's also no other usable event fired, that could be use to put in another delay, right after the opener is pressed. So the only way to fix it, would be to disable the 40y-range-check entirely while being in cat form. And therefore turning it back from 40y to the game default of 28y while in this form.

Would that be hard to implement disabling the 40y range check automatically while in cat form and enabling it back when out of cat?

**Comment by shagu** [comment]
> Would that be hard to implement disabling the 40y range check automatically while in cat form and enabling it back when out of cat?

No, that would be quite easy. It's just that I'm not happy with it at all. I'd like to give myself and others more time to think about it. Maybe there's another solution that I just can't see right now.

**Comment by pabonamu** [comment]
Thanks everyone for the feedback. I tried using a clean client, only installing the latest version of pfui, and went to Zul'Gurub with friends. The same issue still occurred when fighting Hakkar. So I'm pretty sure the problem lies with pfui. It seems like Shagu has already found the issue, looking forward to the day it gets fixed.

**Comment by Sartigen** [comment]
Simply turning off the 40 yr check in the pfui settings worked as @shagu  suggested! I tested it in Naxx yesterday.

**Comment by welpenhund** [comment]
confirmed, worked for me aswell in pve and pvp... sad there is no workaround

**Comment by shagu** [comment]
> No, that would be quite easy. It's just that I'm not happy with it at all. I'd like to give myself and others more time to think about it. Maybe there's another solution that I just can't see right now.

As nothing better came to my mind and also no further ideas came up, I have now disabled the 40y range check while being in cat form. (Cat detection is done by checking for class == druid and powertype == energy)

"Fixed" via: https://github.com/shagu/pfUI/commit/7e0990c4e69aef1a2fdedeee016899835e6c377c

**Comment by welpenhund** [comment]
Could you add a second checkup that doesn't disable the 40y range check as long as the druid is in stealth and/or not in combat? Or is that something that can not be updated like that?

**Comment by shagu** [comment]
No, that would then again eat your first combo point of the opener, due to the stated timing issues.
