### ISSUE TITLE
pfUI displays an incorrect duration for the Expose Weakness debuff (Dragonstalker Armor 8p set bonus)

### ISSUE THREAD

**Issue by patrycos** [shagu/pfUI#1266]
[Expose Weakness](https://database.turtle-wow.org/?spell=23578) is a proc debuff hunters apply to their ranged attack targets if wearing a full set of [Dragonstalker Armor](https://database.turtle-wow.org/?itemset=215). It increases ranged attack power against the target by 450 for 7 seconds. However, pfUI incorrectly displays the debuff duration as 5 seconds.

There exists another [Expose Weakness](https://database.turtle-wow.org/?spell=7140) debuff that is used by some NPCs which increases physical damage taken by the target by 5 for 5 seconds, I suspect this may have something to do with this issue occuring.

**Comment by shagu** [comment]
All debuff timers are only guessed based on the debuff name appearing in the combat log and pfUI's internal database of durations by name. If both debuffs have the same name, there's no way to guess it properly due to the lack of proper APIs and Combat Log features of vanilla. The guessing is already done as good as I could do. However, If you have ideas and the knowledge to do it better, please send a pull request. It would be highly appreciated.
