### ISSUE TITLE
"Enable Durations on Foreign Frames" not working on Luna Unit Frames Target Debuffs unless DebuffTimers is enabled? 

### ISSUE THREAD

**Issue by zmarotrix** [shagu/pfUI#1321]
I'm using [Luna Unit Frames](https://github.com/gnwl/LunaUnitFrames/tree/TurtleWoW) and pfUI shown below. 

![image](https://github.com/user-attachments/assets/c482d5d8-37aa-4d67-bda6-eaf89751ae8c)
![image](https://github.com/user-attachments/assets/f6a48a8c-b14a-4a56-ad00-423e1d5e2e7a)

Here are my cooldown settings in pfUI
![image](https://github.com/user-attachments/assets/bdea56d8-e1ad-4111-8d78-9a8414beb86a)

Cooldowns seem to be working on both the action bars (pfUI) and the Luna Unit Frame Buffs, but not the Luna Unit Frames Debuffs. 

![image](https://github.com/user-attachments/assets/ddfc8180-261d-42ed-9e62-4e54cfb466df)

This was frustrating but not a huge deal because I just enabled [DebuffTimers](https://github.com/Voidmenull/DebuffTimers). 

![image](https://github.com/user-attachments/assets/e350c9f1-9109-4e45-99d0-5c847c45189a)

But when I enabled Debuff Timers, Suddenly the pfUI timers are working beneath the DebuffTimers??

![image](https://github.com/user-attachments/assets/977c45fd-bc4a-465d-9147-ee644dccd370)

![image](https://github.com/user-attachments/assets/0ae01450-5dd8-4cda-92f1-f282acb58a2a)

I know [DebuffTimers specifically singles out Luna Unit Frames](https://github.com/Voidmenull/DebuffTimers/blob/9da80d56175f4772e6f3c59798eec19aea61bed0/DebuffTimers.lua#L555) but I don't understand how that would effect pfUI's ability to see the debuffs? I cannot set DebuffTimers size to 0 or my chat gets flooded with error messages. Is there something I'm missing? Some fix for this situation?

**Comment by zmarotrix** [comment]
Tested with only combinations of these 3 mods enabled and no other mods.

**Comment by shagu** [comment]
The cooldown setting in pfUI adds text to cooldown animations (the circular animation). 
It's like OmniCC, only what has a timer, will get a text field. The pfUI actionsbars, 
and pfUI unitframes have those animations, so it also adds numbers there.

Luna Unit Frames however doesn't have any debuff duration informations, so there's no cooldown frame that could be picked up by pfUI.
For that, you need to enable another addon like DebuffTimers to explicitly extend Luna Unit Frames with debuff durations.
That moment, those debuffs get an animation an pfUI could pick it up if "Enable on Foreign Frames" is enabled.
But DebuffTimers also adds numbers to the cooldown animations, leaving you then with two text-fields on the animation.

I suggest to disable "Enable on Foreign Frames", so that pfUI does NOT put its timer ontop of the timer added by DebuffTimers.

**Comment by zmarotrix** [comment]
Oh I understand, that actually cleared up the confusion. I managed to just modify DebuffTimers to remove the text and that seems to have fixed the issue. I'm sure there's probably a more elegant way to do this but I'll look into that later. 

I'd prefer to have uniform timers across the board than use 2 different timers.
