### ISSUE TITLE
Can't get UI to work

### ISSUE THREAD

**Issue by Antenacht** [shagu/pfUI#1332]
I've been struggling to get this addon to work in my addon folder and am not sure what to do. Everyone I talk to who uses it on Nyctermoon says they just use the default settings and everything is fine. However, mine looks like this (see photo). I'm not sure what to do, or how to correct it. There is also an issue with showing mob health bars constantly, and requiring me to hit "V" but it comes back a few minutes later 

![buggy pfui](https://github.com/user-attachments/assets/2f190c56-91f0-4612-9cfb-c5c4b3f51596)

**Comment by Antenacht** [comment]
![legacy uii](https://github.com/user-attachments/assets/c8eb87a3-6256-4de7-b44e-5036d12a4c3f)
![adapta ui](https://github.com/user-attachments/assets/12b8c441-aece-4c45-af82-c7643a551f86)

**Comment by Antenacht** [comment]
Its strange because I had one that looked like this a few hours ago, which was quite ideal and now its no longer showing up like this.

![ideal ui](https://github.com/user-attachments/assets/b42ebbd4-7c4d-4fdb-ba55-1670916ff94c)

**Comment by shagu** [comment]
Hello, you are running an exceptional low screen resolution. To me it looks like you have 800x600 on a widescreen monitor. Go into Video Settings and use a resolution that matches your monitor. Probably 1920x1080 (Wide).
Also make sure the **entire** game folder is writable, so that it won't revert back to 800x600 after restarting.

For the nameplates, to change the default, go into pfUI settings -> Nameplates -> Show on Hostile Units [ ]

**Comment by Antenacht** [comment]
Hello,
Your email was a great help and led me to the right answer. It was a combination of low resolution and having a box called "Use UI Scale" that was causing the issue. Thank you very much for the quick response as this has been driving me crazy!
________________________________
