### ISSUE TITLE
Heal over TIme, Buff Duration

### ISSUE THREAD

**Issue by Justnova** [shagu/pfUI#1338]
Is it possible to get heal overtime ablites to show their remaining time on a unit? Currently, they only show if the unit has the heal on them or not but there is no timer to show the remaining duration. Is this something that can be fixed?

**Comment by shagu** [comment]
I assume the request is about Vanilla, because on TBC it should show the duration of all buffs perfectly fine.

On Vanilla the client does not tell anything about the duration of buffs. Writing a module that guesses/estimates the buff duration based on a static database is a lot of work and not accurate at all. I will most likely not spend the time doing so.

I'm hoping that client hacks like SuperWoW or UnitXP will someday be able to provide the required API to get nice buff and debuff data (like they do for enemy casts and other nice things).

I leave this open for a while in case someone would like to take over and write something like libdebuff that scans and estimates buff durations.

**Comment by Justnova** [comment]
Thank you for your reply! I totally understand if this isn't something easily done. It was a wish if it was something easy to do, which it does not. Thanks for the great addons! Love them all!
