### ISSUE TITLE
[Feature Request] NPC Titles on Nameplates?

### ISSUE THREAD

**Issue by sunlightFrequency** [shagu/pfUI#1357]
Hello! I've been using pfUI practically since I started playing on Turtle, and it's been absolutely perfect for my needs. Special shoutout to the "disenchant" button in the bags frame. That said, I have a bit of a selfish request to make. 

I'm someone who really likes to play with nameplates permanently on, as the default floating names in the game are very difficult for me to read unless I zoom in really closely. Unfortunately, with most nameplate addons this means that I miss out on some critical information: NPC Titles such as <Innkeeper> or <Trade Goods>. Essentially, I have to toggle my nameplates when I want to search for a specific vendor or NPC, which forces me to look at the blurry in-game names that I have such difficulty with. If it were possible to add these titles to the pfUI nameplate display, my eyes would thank you very much for it, haha.

Also, I'm not fully familiar with the etiquette regarding necroposting on Github, so I decided to make my own request for this as [the original post](https://github.com/shagu/pfUI/issues/1223) that mentioned the feature I want was marked as Stale. Much love for your tireless work on your addons, and I hope you are staying healthy and hale in these trying times. <3

**Comment by shagu** [comment]
Hi, the problem here is that regular nameplates in vanilla don't have access to those informations that would be required. 
It would be another feature that only works if the player has the SuperWoW mod enabled. It's quite some time effort for something that I don't want to use or need at all and also only works for a small subset of users after all.

I'm not saying that I will never do that, I'm just saying that it's a workaround that requires the client to be modified for something that already works stable and less wonky if the nameplats are just disabled for friendly units. So the priority of it will be very very low for it. Also all those `if superwow_active then` parts everywhere are starting to get more and more ugly in the code.

In the meantime, make sure you use the best video resulotion in game that your monitor offers, i personally never had issues with the readability of the 3d-world texts. Maybe that helps already to improve the situation for you.

I will keep this issue open for now, but can not guarantee that I'll work on it in near future.

**Comment by sunlightFrequency** [comment]
Ahh, I understand. I didn't realize it was an issue with the game itself, thank you very much for the explanation. :)
