### ISSUE TITLE
Debuff timers?

### ISSUE THREAD

**Issue by Oliveryo** [shagu/pfUI#136]

**Comment by shirsig** [comment]
Renew made this https://github.com/Voidmenull/EnemyBuffTimersVanilla (https://forum.twinstar.cz/showthread.php/116773-Addon-EnemyBuffTimersVanilla-Luna-Fork) which seems to be compatible with pfUI, though I haven't tried it. However, note that debuff timers are impossible to do perfectly using the vanilla API. This particular addOn simply uses a static list of durations which is the simplest and least correct way to do it. If you want the best possible timers (afaik) in Vanilla you can try my https://github.com/shirsig/aurae which takes into account things like diminishing returns and how they're shared, tries to refresh durations as well as can be done using the player cast events etc. It is not integrated with any unit frames but that is kind of by design as it makes no sense to limit the display to your target in some cases like, e.g., polymorph). I guess the ideal PvP UI might combine something like this http://iliana-sc.github.io/enemyframes/ with debuffs, but that would be a lot of work and there is nothing comparable at this point.

**Comment by Oliveryo** [comment]
Thanks for your great answer and thanks for your work.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/issues/27
