### ISSUE TITLE
[TurtleWow 1.17.2] The height of the left chat panel changes abnormally.

### ISSUE THREAD

**Issue by Eachiin** [shagu/pfUI#1365]
**I use pfUI 5.4.10  on the turtle 1.72.** 
The height of the left chat panel changes with certain actions (like riding a horse). When I click on the panel title, it returns to normal. How can I fix it?
![Snipaste_2024-11-10_16-14-40](https://github.com/user-attachments/assets/0c553b29-a634-4b9d-8d42-80293c64f9d3)
![Snipaste_2024-11-10_16-15-19](https://github.com/user-attachments/assets/68493c2e-2a1c-4250-a254-6613f17ab775)
![Snipaste_2024-11-10_16-15-49](https://github.com/user-attachments/assets/d69c5cfa-41c2-42e7-96dc-9625870277fa)

**Comment by shagu** [comment]
> **Why is my chat always resetting to only 3 lines of text?**  
This happens if "Simple Chat" is enabled in blizzards interface settings (Advanced Options).
Paste the following command into your chat to disable that option: `/run SIMPLE_CHAT="0"; pfUI.chat.SetupPositions(); ReloadUI()`

https://github.com/shagu/pfUI?#faq

Also make sure to not have any conflicting chat-addons installed.
