### ISSUE TITLE
Chat Copying

### ISSUE THREAD

**Issue by dripfeeder** [shagu/pfUI#1389]
Hello,
I have two chat windows: three chat tabs on the left and one on the right. When I click the "copy" chat button, I can only select text in one window and one tab. If I restart the game, the issue persists, but it happens with a different tab this time. Is this a bug, or do I have something set up incorrectly?

![image](https://github.com/user-attachments/assets/53ba4bd4-26af-40ca-80fd-d1cf755d4fc0)
![image](https://github.com/user-attachments/assets/ebc96204-0d4d-43a0-a24f-d391c3c99650)
![image](https://github.com/user-attachments/assets/af60078c-f90a-4bf8-b160-175272c3cc6e)

So, it works in one "General" tab, but not in the others.

**Comment by shagu** [comment]
Hello,

The "copy" feature does only work for the messages you received this session. It does not contain messages that are provided from the chat history. So after reload it's pretty normal to not have text there. Also, for the Combat Log, it is intended to not be filled due to performance reasons. (Pushing every combat message into an editbox kills the FPS)

With that in mind, please try again if the copy window really doesn't work on other chats.

I'm using "General", "Combat Log", "Whispers" and "Loot & Spam". The copy feature works as intended on all but "Combat Log".

**Comment by dripfeeder** [comment]
Got it, thanks for the response.
However, my "Loot&Spam" tab stays the same as shown in the screenshot above, even within the same session.
Alright, maybe I’m doing something wrong on my end.
Either way, thank you for the addon, and all the best to you!
