### ISSUE TITLE
Some enhancements for a few things?

### ISSUE THREAD

**Issue by Frodeur77** [shagu/pfUI#175]
Hello Shagu, would it be possible to add combo points on nameplates so rogues would not have to look on the player's/mob's plate?

I havn't seen any options to see my caracter level on my player icon, is it available?

I can see energy ticks while at 100% energy but not while spending energy in combat, so it's not that usefull to enable the energy ticks in the menu.

That's all i have for now, your pfUI is awesome thank you.

**Comment by shagu** [comment]
Hi,

I'm not sure if combopoints on nameplates are that usefull in classic, because they will reset on every target change.

There is no character level on player's unitframe, will be handled within this report: 
https://github.com/shagu/pfUI/issues/40

There was a bug, energy ticks should be always visible. https://github.com/shagu/pfUI/commit/db4be366b33cad90590ed5049ead7a1085b2e958
