### ISSUE TITLE
Inventory doesn't stay open for more than a few seconds in battlegrounds

### ISSUE THREAD

**Issue by Cephel** [shagu/pfUI#255]
I recall a similar bug on the addon Onebag. If the pfUI implementation is similar, I'd suggest you switch to Bagnon instead.

**Comment by shagu** [comment]
First, let me quote the Addon's description:
>  It is completely written from scratch without any inclusion of 3rd party addons or libraries.

It does not and will not use any of your addons you suggest.

Secondly. I can't reproduce nor fix a "random" happening thing. 
How should I do that? Join a battle ground and stay there for 30 minutes? 2 hours? A Day? With bags open just waiting for the "random" magic appears? 

Sorry but I won't even start debugging with such a bad description.

**Comment by Cephel** [comment]
It takes 30 seconds inside of AV for it to happen like 10 times. The inventory doesn't even stay open for more than a few seconds.

It is literally identical to the same bug on Onebag. And switching the implementation isn't the same as adding a dependency.

**Comment by shagu** [comment]
> It takes 30 seconds inside of AV for it to happen like 10 times.

This should be in the main description.

> It is literally identical to the same bug on Onebag. And switching the implementation isn't the same as adding a dependency.

Tell me, what is the "implementation" that is used by OneBag? 
How does it differ from the one in Bagnon? Please put it in words, because I can't. 
They are 2 completly different addons.

I won't start comparing 22106 Lines of code (OneBag) with another 5828 Lines of code (Bagnon) just to see what they've done different in "implementation", and then going to rewrite the complete bag module.

Instead, I'd prefer to search the root cause of this problem and just fix it.

**Comment by shagu** [comment]
Does this also happen in Warsong Gulch and Arathi Basin?

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/4726c93c3002b443db32ef3a9dafa42a18a7ee8a

**Comment by shagu** [comment]
Fixed.
