### ISSUE TITLE
/pfcast does not work with some spells

### ISSUE THREAD

**Issue by Z1mmey** [shagu/pfUI#278]
Hi Shagu,

I only tested this with the German language pack, but there seems to be an issue when creating a /pfcast macro with a spell that contains a blank character (like "Große Heilung" or "Machtwort: Schild").

The spell is simply not cast.
Other skills seem to work fine (altough the missing CD without the workaround mentioned in issue #196 is annoying)

Thanks!

**Comment by Road-block** [comment]
The spell name must be exact and not included in quotes.  
Shift-click it from the spellbook into the macro frame to make sure then change the /cast to /pfcast.  
There is a typo in https://github.com/shagu/pfUI/blob/master/modules/mouseover.lua#L4
~~SLASH_L~~PFCAST2 instead of SLASH_PFCAST2 so make sure you're using the /pfcast and not the /pfmouse version.

**Comment by Z1mmey** [comment]
That is exactly what I did - as I said, it works fine for spells that do not contain a " " (blank) character.
Maybe it's an issue with the German localization.

**Comment by Road-block** [comment]
It could be a localization issue but it's strange. I tried it with a couple warrior spells with spaces in the name (Thunder Clap and Sunder Armor) and had no issues.

What happens if you `/run CastSpellByName("Problem Spell")` in a macro or in-game chat?  
This is the same command pfUI is using internally, so that would point to an issue with the client (or the chat parser somehow mangling the spell name)

**Comment by Z1mmey** [comment]
I rewrote the macro by Hand instead of copying the spell name from the spell book and now it works.
No idea why this happened, but thanks anyway for your help.
