### ISSUE TITLE
Implement retail ElvUI minimap consolidated buff bar

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#366]
Here's a visual of it: https://youtu.be/p2IjfWVwwPA?t=10m7s
And here's a ElvUI 1.12.1 backport with it: https://www.youtube.com/watch?v=HhGYjj3MKxc (though the author went completely missing and never released his project... sooo rip)

What it does is to show all usual raid buff icon beside the minimap (such as Mark of the Wild, Power Word: Fortitude etc.) their icon is shown even if you don't have the buff, then when you get the buff it'll start a text timer and a animation timer on the icon. (The same animation as abilities when they're on your action bar and on CD)
So it's pretty much a feature to easily keep track of buffs when you're raiding etc.

**Comment by crumdidlyumshis** [comment]
omg yes 👍 What ever the effin eff happened to that icum0nu dude?? I would have thought for sure he would have released his code before dropping off the face of the earth... bug dang that was a seriously legit backport of ElvUI that I never thought would be possible. At least @shagu has saved our ElvUI anxieties 🍰

**Comment by shagu** [comment]
Does this really make sense? On retail they have merged several buffs into one (like +10% attackpower). I believe it would be way to many buffs in vanilla. Please give me a complete list of buffs that I should add in your opinion, then I'll decide.

**Comment by mytelefe** [comment]
There is VCB aka Vanilla Consolidated Buff-frames addon developed https://github.com/Geigerkind/VCB
In raid you should use oRA or something similar to check whole raid for buffs anyway. 
I dont want to come as ballbuster here because I think it could be neat and stylish addition to the ui just not very essential.

**Comment by Cruzix** [comment]
Hmm let's see how many class buffs there is though
1. Mark of the Wild
2. Power Word: Fortitude
3. Divine Spirit
4. Arcane Intellect 
5. Paladin buffs; salv, kings, wisdom and might. I guess something fancy could be made here where 1 icon tracks all 4 of them
6. Shaman totems (hmm should this even be tracked on that bar as its not a buff)
7. Warrior shout
8. Hunter Trueshot Aura (maybe merge 7 and 8 and make something fancy too)
So thats 6-7 icons depending if you count shaman totems and if you merge trueshot+shout. 

Maybe far down the road this could be implemented as its not a priority thing at all... if the demand is high enough for it?

**Comment by Cruzix** [comment]
Well actually to be perfectly honest, I'm not even sure I'd be using this feature myself because of VCB... I might've been too fast on posting this afterall xD 

But I still think its a neat feature and there's probably other people that would like it a lot, up to you @shagu

**Comment by shagu** [comment]
> Paladin buffs; salv, kings, wisdom and might. I guess something fancy could be made here where 1 icon tracks all 4 of them

You shouldn't track it with only one icon. Because most of the time you won't have all 4 buffs.
And if the icon is shown as soon as 1 buff is active, it would be pretty useless.

> Shaman totems (hmm should this even be tracked on that bar as its not a buff)

Yes, should. they provide an aura like the hunter does, would be inconsistend to drop them.

```
1. Mark of the Wild
2. Power Word: Fortitude
3. Divine Spirit
4. Arcane Intellect
5. Kings
6. Might
7. Widsom
8. Salvation
9. Warrior shout
10. Trueshot Aura (maybe merge 7 and 8 and make something fancy too)
XX. + Totems + Elixir + Flask + Bufffood + Temp. Weapon Enchant
```

Even without Totems, Flasks, Elixirs and Bufffood, there would be 10 Icons for now. 
I'm sure, if you would *only* track the usefull buffs for your class, you will end up with about 10.
I don't know how big you're going to scale your minimap, but for the default setup, there is no space to add 10 or even more buffs to the minimap square.
