### ISSUE TITLE
Catastrophe! 

### ISSUE THREAD

**Issue by TinyLittleBits** [shagu/pfUI#386]
I'm glad I didn't empty the recycle bin.

The last commit 389a7b6  forbids to place some elements like action bars or pet bar out of the screen view and as I can't resize the action bars to have only a few icons that was the only way to display 3 icons for example. same with the pet bar, I don't need to see it but if I hide it then the hotkeys do not work anymore.

So I really hope you'll still allow us to place any element of the UI at the edge of the screen and having its most part out of the screen view.

It's very important to me and the reason I won't update anymore till this is reestablished as it was before or permit us to change the numbers of buttons per action bar or hide them while keeping the hotkeying functional.

**Comment by gamer4eg** [comment]
END OF THE WORLD (c) of the Lich King

**Comment by TinyLittleBits** [comment]
visibly nothing will be done for that and the author seems to do not care at all about our feedback.

**Comment by crumdidlyumshis** [comment]
With a title and description like that, I am not sure who wouldn't take that seriously. 🥇

**Comment by shagu** [comment]
Sorry for having a job and not beeing able to fix your issues immediately.

**Comment by TinyLittleBits** [comment]
in case you didn't see: I edited and closed that issue so I have no more and decided to leave you, your UI and your own issues and you can shove your sarcasm in whatever hole of your body of your choice.

**Comment by shagu** [comment]
I'm doing this project in my free time, it's for fun, it's a hobby.

What did you expect from a free project that is done by a single guy in his spare time? Enterprise grade support hotlines? Guaranteed respones times?

To be honest, I'm glad you leave. I don't want to have people here, that get bitchy whenever I did not answer within 12 hours...

Maybe someday you'll understand how much work a project like this is about for a single person. Maybe someday you start to respect other peoples work and maybe you even be patient and write issues in a kind manner.

In the meantime, I wish you all the best.

PS: here's the fix, because the issue was valid and already ontop of my todo: https://github.com/shagu/pfUI/commit/096ee9d469056e7b0634005bcd1a3f3bbe67341c
