### ISSUE TITLE
DPSMate checkbox

### ISSUE THREAD

**Issue by dikdigguh** [shagu/pfUI#42]
Not sure if it's only affecting me, but the DPSMate toggle seems to be behaving opposite of the other third party addons. So when it's checked DPSMate is hidden. When it's unchecked, it's shown.

Cheers Shagu!

**Comment by shagu** [comment]
When it is checked, DPSMate is integrated into the Right check (click the "Hide" button). While unchecked, pfUI does not affect anything in DPSMate. Works as intended so far.

It might be confusing because, when checked, DPSMate is hidden and only shown when you click the chat-button. And when disabled, DPSMate is shown somewhere on the screen.

**Comment by dikdigguh** [comment]
Ah, thanks for the explanation!

**Comment by Geigerkind** [comment]
If something is wrong with DPSMate, feel free to leave a issue report :>
