### ISSUE TITLE
Blizz Castbar Bug Hunter

### ISSUE THREAD

**Issue by Sheezhyn** [shagu/pfUI#471]
There appears to be a bug with the Blizzard Castbar, when using pfUI (latest version v2.0.4). It is disabled in the pfUI-settings, however it is still being used for the "aimed shot". Seems to be a hunter-only problem.

[http://imgur.com/iz9B5Xe](url)

**Comment by Cruzix** [comment]
This is due to pfUI not using the same type of "Aimed Shot Support" as [YAHT](https://github.com/Aviana/YaHT)/rais_autoshot.

You can fix this by toggling off the aimed shot and multi-shot support from YAHT so it uses pfUI's build-in support for them.

![image](https://cloud.githubusercontent.com/assets/6162744/23699008/eb524d04-03ed-11e7-9240-e5104f0d9100.png)

**Comment by Sheezhyn** [comment]
Thank you for your quick response.
