### ISSUE TITLE
EQL tracker font size

### ISSUE THREAD

**Issue by Shotgunsaint** [shagu/pfUI#603]
I am using pfUI with EQL3.  I am using the pixel perfect option, which requires me to increase the size of fonts for readability.

The text size on EQL3 tracker and quest log is very small.   There is an option in EQL3 to increase font size but it does not seem to do anything while pfUI is active.
![image](https://user-images.githubusercontent.com/17935084/28487418-cd16e59c-6e4c-11e7-9eb0-1ee3789204ad.png)

**Comment by Cruzix** [comment]
tbh I'd rather like to see something similar to EQL being implemented into pfUI

It's such a handy addon that almost everyone has because it makes the quest log so much more easier to both read and browse. Although the EQL addon has so many useless and not working features so a rewrite from @shagu that is implemented into pfUI would be amazing

**Comment by Road-block** [comment]
ShaguQuest embeds a version of EQL3

**Comment by Cruzix** [comment]
Welp, port it over already then @shagu :D 👍

**Comment by shagu** [comment]
You should scale your Interface via the UI-Scale Option in the Video Settings rather than trying to modify the font of every addon on your own. Because that's exactly the reason why UI-Scale exists. It scales your whole interface at once to gain a readable result on every display-size.
