### ISSUE TITLE
Laggy

### ISSUE THREAD

**Issue by Ulkie** [shagu/pfUI#610]
Love this UI, but when in raids certain fights make my fps shoot between 0 and 5 and also shows me as lagging, fight becomes completely in playable. What's worrying is that its at its absolute worst during Barron Geddon and Vaelstraz when the first living bomb/ burning adrenaline gets cast my fps/ms shoots up to unplayable levels.

**Comment by Sqoops** [comment]
If you are not a healer try to disable the Raid Frames. I'm playing on a Laptop with the same problem - with Raid Frames disabled my FPS stay at 30 and wont drop below.
Go to settings - Group Frames - Raid - and uncheck "Display Raid Frames"

I think it drops so low because all 40 raidframes get refreshed every single frame - so 30 times a second if you have 30 FPS. Shaqu could implement an option to let the user set how often the raidframes will be redrawn - for example only 2 times per second (every 500ms)


Lunaframes has a similar implementation:

local function UnitWatchOnUpdate()
	this.time = this.time+arg1
	if this.time > 0.3 and not Units.pauseUpdates then
		this.time = 0
                ... do stuff
	end
end

**Comment by Cruzix** [comment]
A "minimize" button would be sick too - similar to how it is on modUI's raid frames. So you can always minimize it on the go since its not always that you need to see raid frames.

**Comment by shagu** [comment]
OnUpdate is used for the animation to provide smooth transitions between two values. Updating the animation only twice per second won't be a solution.

**Comment by Road-block** [comment]
It might be an interaction with some other addon.  
I'm using pfUI + HealComm + DPSMate + BigWigs + oRA2 to mention the major raiding addons and a bunch of utility addons and have no significant FPS drops (I play with my framerate locked @64fps).  
At least for Baron Geddon, haven't tested on Vaelestraz yet.

**Comment by byaka** [comment]
For me, major frame-drop was caused by ShaguCopy. After disabling this addon problem gone.

**Comment by Road-block** [comment]
@byaka That reminds me. I've edited my local ShaguCopy some time ago to make it skip the CombatLog ChatFrame.  
Should have mentioned that but it slipped my mind, so you might have something there.

**Comment by byaka** [comment]
@Road-block, can u share it?

**Comment by Road-block** [comment]
```lua
for i=1,NUM_CHAT_WINDOWS do
  if i==2 then
    -- skip combatlog, use /combatlog to spool to disk
  else
   -- all previous code
  end
```

**Comment by byaka** [comment]
thx, will test this

**Comment by byaka** [comment]
@Road-block this fix works like charm, thx u!

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/issues/519
