### ISSUE TITLE
GUI ruRU localization

### ISSUE THREAD

**Issue by Lichery** [shagu/pfUI#621]
I translated gui into Russian.
Please added this in pfUI.toc :
> ## Notes-ruRU: Полная замена интерфейса пользователя.

Also I added a missing itemtype:
["INVTYPE_BOW"] = "Bow",
I'm not sure if he's needed there or not. Just noticed that the bow was not indicated and decided to add it.
Look, I wrote everything correctly?
And i added a missing critter:
'Dig Rat',

I added this strings only in locales_enUS.lua and locales_ruRU.lua files. Need to add it to other files.
[ruRU.zip](https://github.com/shagu/pfUI/files/1216005/ruRU.zip)
[locales_enUS.zip](https://github.com/shagu/pfUI/files/1215358/locales_enUS.zip)

P.S. Sorry for my bad English...

**Comment by shagu** [comment]
Your translations are now included here: https://github.com/shagu/pfUI/commit/88a66232ccbaefb2d7183c8f3a89b9a3726f9d10

I didn't applied your other changes, because:
- `INVTYPE_BOW` is not requried because they are identified by `INVTYPE_RANGED`.
- `Dig Rat` is not in the critters list, because it is required as a quest objective.

Thanks alot for your effort. :)
