### ISSUE TITLE
debufftimers: regex error on latest russian client

### ISSUE THREAD

**Issue by Lichery** [shagu/pfUI#625]
On the Russian client when using any spell an error:
![bandicam 2017-08-10 21-34-37-911](https://user-images.githubusercontent.com/24303693/29186133-2945b916-7e14-11e7-95b7-51c1d523be6d.jpg)

UPDATE:
This error only occurs when direct damage. (Searing Pain, Shadow Bolt etc)
DoT damage, direct healing or HoT does not cause an error.

**Comment by Lichery** [comment]
If necessary, I can provide russian GlobalStrings.lua

**Comment by shagu** [comment]
weird, that's in SPELLREFLECTSELFOTHER.. ("Your %s is reflected back by %s.")
I'll have a look

**Comment by shagu** [comment]
I'm not able to reproduce that with any spell

**Comment by Lichery** [comment]
No, checked only with pfUI

**Comment by Road-block** [comment]
"Ваше %s отражено назад персонажем %s."
Only thing that comes to mind is some UTF tomfoolery that causes one of the spell or player names to put an extra `%<magic char>` into the string.  
That error means there is an out of bounds capture (i.e. an extra format specifier that doesn't match the captures)  
To have a chance to properly debug it shagu would need the exact combatlog line that fails, including the spell name **and** the player or npc name that does the reflection.

**Comment by shagu** [comment]
As @Road-block said, I'd need more information on this. 

Especially due to the fact that there wasn't a ruRU client around during the classic times and all russian clients that exist are some `translation hacks` that have been made later on, I might not be able to reproduce this on the client I'm currently using. The ruRU-client I use is `1.12.1 (5875) translation version of 24.08.2014`. If you're using another client, please share a link to the download (via discord or mail) otherwise I might won't be able to reproduce and fix this.

**Comment by Lichery** [comment]
Shagu, you have an old client version. The last update of the client is on 05/09/2016. Please download the new version from here: https://vk.com/wowruru

**Comment by Lichery** [comment]
Here's my version GlobalStrings [GlobalStrings.zip](https://github.com/shagu/pfUI/files/1254574/GlobalStrings.zip)

**Comment by KasVital** [comment]
shagu hello, check this please:
english version: "Your %s is reflected back by %s.";
russian version(latest): "%2s отражает ваше заклинание \"%1$s\".";

**Comment by KasVital** [comment]
"%1$s"." spell
%2s        mob/player

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/a89566905104ee92610d7c5e1a50dcb3e2053c3c
