### ISSUE TITLE
api: unitframes.lua:1380 attemp to index field `?' (a nil value)

### ISSUE THREAD

**Issue by calymnestor** [shagu/pfUI#660]
Hello
I have the following problem:
always show up in the chat error messages like this:
ERROR: Interface\AddOns\pfUI\api\unitframes.lia:1380 attemp to index field `?' (a nil value)
This happens whenever a mob appears. In the screenshot for example
"Oberrichter Grimmstone" BRD Screen 1
"Baron Glutart" UnGoro Screen 2

How can I solve this problem?
Thanks in advance

![error](https://user-images.githubusercontent.com/31406093/30635651-5e94a66e-9df3-11e7-9a79-6a2c82e09783.jpg)
![wowscrnshot_090917_231254](https://user-images.githubusercontent.com/31406093/30635944-4479af76-9df4-11e7-9f7b-65983e3750d7.jpg)

**Comment by shagu** [comment]
Hi, are you running the latest version? (not release)

**Comment by calymnestor** [comment]
Thank you for your quick response.
I now have the latest version.
The error message looks exactly the same, but with a different number:
ERROR: Interface\AddOns\pfUI\api\unitframes.lua:**1420** attemp to index field `?' (a nil value)

![error sengende schlucht](https://user-images.githubusercontent.com/31406093/30659466-29cf7eb8-9e3e-11e7-8158-88b323661357.jpg)

how can i attach the unitframe.lua file to this Ticket?

Thanks, Calymnestor

**Comment by shagu** [comment]
Thank you for the quick update. You don't have to attach the file anymore.
There seems to be an issue regarding the class color detection of some mobs.
Did you already tried to reproduce that with all other addons disabled?

**Comment by shagu** [comment]
I'm trying to reproduce this, but I'm not able to:
![unitframe-issue](https://user-images.githubusercontent.com/11586807/30663136-ef5cb4e2-9e49-11e7-87be-406d47a38568.png)

**Comment by calymnestor** [comment]
all addons are disabled
![addons](https://user-images.githubusercontent.com/31406093/30663779-10ec2aa0-9e4c-11e7-81db-e6351c2a45d9.jpg)
the same error
![sengende schlucht ohne addons](https://user-images.githubusercontent.com/31406093/30663821-2bb03c5a-9e4c-11e7-85b1-e9ee973cf137.jpg)
then I deleted the WTF folder
![sengende schlucht wtf geloscht](https://user-images.githubusercontent.com/31406093/30663847-40618a00-9e4c-11e7-9f1a-e5b4adeaf034.jpg)
The error is no longer displayed

Must probably configure everything again or?^^

**Comment by calymnestor** [comment]
Class IS the problem. I have disabled this, and the error message is gone
![class](https://user-images.githubusercontent.com/31406093/30664425-fb40f8be-9e4d-11e7-9596-cd1a9c1d0dfe.jpg)

Thank you for your help!!

**Comment by shagu** [comment]
Could you do me a favour and please add `if not class then class = "WARRIOR" end` to line 1420 in unitframes.lua?

The result should look like:
```
  elseif preset == "class" and config["classcolor"] == "1" then
    local _, class = UnitClass(unitstr)
    if not class then class = "WARRIOR" end
    r = RAID_CLASS_COLORS[class].r
    g = RAID_CLASS_COLORS[class].g
    b = RAID_CLASS_COLORS[class].b
```

**Comment by calymnestor** [comment]
I have now added this command.
now the error message has changed:
![neuer comand](https://user-images.githubusercontent.com/31406093/30666072-798dc940-9e53-11e7-9e3c-9397342cefee.jpg)
must now unfortunately off, am on Friday evening again there
Thank you for your help

**Comment by shagu** [comment]
Oh.. It looks like your server doesn't return an unlocalized UnitClass. On which server does this happen?

For further testing, you could create the following macro and use it on one of the mentioned mobs:
`/run local a,b = UnitClass("target"); message((a or "nil") .. " - " .. (b or "nil"))`

I'm curious what the output will be.

Thanks for your effort, have a nice day :)

**Comment by Road-block** [comment]
I haven't looked at context so I might be totally off but on retail at least during classic UnitClass(unitId) did not return a class for NPCs, only for players. It instead returned the NPC name (localized version) and nil for the second return.  
If some emulator is returning a class for NPCs, that's a problem (custom change) with the emulator.  
_Same as some private servers for example return accurate NPC hitpoints and mana._

**Comment by shagu** [comment]
Oh really? That's very interesting. I'll have to change some fallbacks then. Because on every server I was so far, there was a fallback to "WARRIOR".  And also in the screenshot, there is clearly "Krieger" in the class field (german for Warrior). 
So I don't get why should the server return "Krieger" as a first value but no "WARRIOR" as a second value?

**Comment by Road-block** [comment]
I'm 99% sure about UnitClass not returning an actual class for NPCs in classic because I had an addon for adding a "class" statusbar to the target frame and I was specifically checking for `not UnitIsPlayer(unitId)` so I could fallback to UnitCreatureType which kept the statusbar useful for quickly deciding if it can be CC-ed by x class etc ..  
Looking at addon code from 2006 and seeing the comments about that.

**Comment by shagu** [comment]
Yes, I 100% trust in you. Also the wowprogramming site tells the same and I'm going to fix that. But I'm still wondering why a server should return the localized "warrior" as first and nil as second variable.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/d290ddd26dddbd6bd35b56aa044c506450ca7023

**Comment by Road-block** [comment]
> Yes, I 100% trust in you. Also the wowprogramming site tells the same and I'm going to fix that. But I'm still wondering why a server should return the localized "warrior" as first and nil as second variable.
I can hazard a guess that some emulators are doing that due to confusing the internal baseclass denominations sniffed from packets [Creature_template#unitclass](https://github.com/cmangos/issues/wiki/Creature_template#unitclass) (using cmangos as an example) but that doesn't mean that the client API returned class.

**Comment by shagu** [comment]
Was able to reproduce this issue on elysium realms on shaman totems and dead silithid eggs. 
The mentioned macro above returns: nil,nil.
This seems to be a server bug as the server should never return nil but should instead return the unitname for non-players or classless units: http://wowprogramming.com/docs/api/UnitClass

It's fixed with this commit, where the class now falls back to "UNKNOWN":
https://github.com/shagu/pfUI/commit/db762a625c0a3a5d33bbe6a72a9ff325572c7f69

![nil-class](https://user-images.githubusercontent.com/11586807/30749142-c7cf92ae-9fb2-11e7-9712-2cf0b6e91a4e.jpg)
