### ISSUE TITLE
core: add support for setups without scrollwheels

### ISSUE THREAD

**Issue by cryptopsy0** [shagu/pfUI#669]
in the latest version. i can't scroll down in the menu, to go to the lower options. I'm trying by clicking the arrow facing down. What should i do? Playing on the elysium server.

**Comment by cryptopsy0** [comment]
i've spoken to some people in game and they confirmed it. the difference with them being they have real mice instead of a trackpoint like on a laptop. So they just scrolled with the mouse wheel instead of clicking with the mouse on the down triangle. Also keyboard scrolling didn't work for them.

**Comment by Aguilaa** [comment]
On a side note,  scrolling speed for the chat - is that changeable?

**Comment by cryptopsy0** [comment]
scrollign works when i install the mouse drives that let me scroll with middle mouse button. But this isn't ideal because then i can't middle-click to open links in my webbrowser.

**Comment by Road-block** [comment]
Just a note that this is more of a _missing feature_ kind of deal, not a bug.  
Those scroll indicators are decorative they have no click handlers, they're just there as a visual indicator that the content is scrolled.  
They don't actually _do_ anything when clicked.

**Comment by cryptopsy0** [comment]
i can see why you would call it a missing features -- becaues it is missing -- , but its more than a feature. It is missing functionality. Not everyone has a scroll wheel.

**Comment by cryptopsy0** [comment]
Neither arrow, neither scroll by arrow keys, neither a scroll bar is present. Don't mislabel it a missing feature. A missing feature is something that enhances gameplay. A bug is when something doesn't work. I can't access the bottom options by any means. Therefore it is a bug.

**Comment by Road-block** [comment]
I wasn't making an assertion about the severity or whether another way (than mouse-wheel) should be added 😄   
I was just saying that it is not unintended behavior of an existing feature (i.e. a "bug").  
At the moment it is by design (ie there is no code that would make the scroll indicators functional).  
Should it change? Sure.

**Comment by Road-block** [comment]
Until @shagu gets around to deciding how he wants to handle this you can open **pfUI/modules/gui.lua** in a proper text editor (that shows line numbers) and replace the section starting at [line:92](https://github.com/shagu/pfUI/blob/a0ec4490a3dceb5c0009b20d6f511bc08d716119/modules/gui.lua#L92) and ending at [line:127](https://github.com/shagu/pfUI/blob/a0ec4490a3dceb5c0009b20d6f511bc08d716119/modules/gui.lua#L127) with the contents of [this gist](https://gist.github.com/Road-block/40293af698261a202f311f398eccbef2).  
That will allow you to click the scroll indicators to scroll up and down.  

_Using the keyboard to scroll (like you do for chatframes) is not possible without creating dedicated keybinds for that (i.e. not practical; your keybinds menu would soon be filled up with scrollframe binds if every scrollframe needed to be usable with keyboard)_

**Comment by shagu** [comment]
I have the same view as @Road-block already said. It's not an unintended behaviour of existing code and therefore does not match my definition of a "Bug". I'd also like to mention that the game requirements lists **Keyboard and Mouse** since the beginning of the first release of World of Warcraft. It's also quite hard to find a mouse nowadays without a scrolling ability and I never thought about that being an issue.

I guess you can expect an update on this soon as it looks like a minor change.

PS: I always thought that I'm a minority playing with the touchpad of my notebook very often, I'm happy to meet someone who pushes that to the next level by playing with a trackpoint. :grinning:

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/74d1bfb9733ac78ec4447e6611d7a8ee43281de1

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/6eaa820c4860cdde5a93e0a562120d9a5a189c26

**Comment by cryptopsy0** [comment]
how is it not a bug when you can't use the program as intended? Explain to me how i'm supposed to set those settings when i can't scroll down.

**Comment by Road-block** [comment]
The issue was fixed within a day of being reported, are you complaining for the sake of complaining now?  
You can click the arrows in the latest alpha, that's how you set those settings.
