### ISSUE TITLE
setting options change ui scale

### ISSUE THREAD

**Issue by cryptopsy0** [shagu/pfUI#672]
Anytime you change a setting, pfui restarts. And when that happens, it causes wow to changes UI Scale to the smallest value, 0.63 i think. I need it 1.0 to see anything because my resolution is very high.

**Comment by Road-block** [comment]
pfUI respects my uiScale value, no changes to it after a reloadui.  
The only thing that changes uiScale in pfUI and that cannot be avoided is when enabling the "pixelperfect" setting.  
This is because wow textures cannot align perfectly at all scales, it is a technical limitation.  


The way to avoid pfUI changing your scale is to disable pixelperfect.

**Comment by shagu** [comment]
As @Road-block said.

**Comment by cryptopsy0** [comment]
How do you disable pixelperfect?
@shagu do you need me to record a video of it happening? its clearly screwing up scale when it restarts.

**Comment by shagu** [comment]
![pixelperfect](https://user-images.githubusercontent.com/11586807/30883915-06d5b8e4-a30e-11e7-8145-ba092d323fad.png)

**Comment by Prequent** [comment]
Thank you. This was super frustrating and disabling pixel perfect fixed it!
