### ISSUE TITLE
Sw_stats broken after introduction of yesterdays commits

### ISSUE THREAD

**Issue by vashin1** [shagu/pfUI#698]
https://imgur.com/a/MhqM2

not sure what the culprit is.

**Comment by Road-block** [comment]
That's not the first error.  
The problem is I added a new entry to the RAID_CLASS_COLORS global table and SW_Stats has a hardcoded class table of itself and doesn't check that the two match.  
It's an easy fix on that side but since SW_Stats is essentially a _dead_ addon that hasn't seen any development since 2006 it's probably better to fix it on pfUI's side.

**Comment by Aguilaa** [comment]
What would needed to be added to sw_stats for this to function?

**Comment by aixiu** [comment]
How can I work properly? Two days ago the version is good. I have encountered problems that can not run.

**Comment by Road-block** [comment]
Well the simple fix on SW_Stats side is to open SW_core.lua and replace the code around line 279 with
```lua
		-- 2.0 why not use the colors blizzard provides for classes...
		for k,v in pairs(RAID_CLASS_COLORS ) do
			if SW_Settings["Colors"][k]~=nil then
				SW_Settings["Colors"][k][1] = v.r;
				SW_Settings["Colors"][k][2] = v.g;
				SW_Settings["Colors"][k][3] = v.b;
			end
		end
```
Like I said though, give us a little time to fix it on pfUI side.

**Comment by shagu** [comment]
The fallback value for unknown classes is now set via meta-table. https://github.com/shagu/pfUI/commit/90c6fefd2d093870eed921b68cda0f9a9c46220e

**Comment by aixiu** [comment]
@shagu @Road-block .Thank you for making a great contribution to pfui
