### ISSUE TITLE
Left chat snaps into wrong size

### ISSUE THREAD

**Issue by pawelkw** [shagu/pfUI#729]
I don't know how to explain it to be honest...
Please just see the video. https://youtu.be/d3tf64OBtSM
Draging and dropping it back in fixes it but only for a while. Then it's back to what you see at the beginning.

**Comment by pawelkw** [comment]
More info:
Latest master (as of yesterday).
Happens in default settings.
Changing font size, frame positions, and some other random stuff doesn't fix it.
Screen res is 1920x1200 (wide).

**Comment by pawelkw** [comment]
Found a reproducible scenario.
I'm a Warlock. When i order my pet to follow me (2nd pet bar slot) then it happens.

**Comment by shagu** [comment]
It looks like you haven't ran the firstrun-dialog or have selected to **not** automatically adjust the chat windows there.

**Comment by craigmoussa** [comment]
Everytime a quest is updated due to getting new loot item etc, it resizes to a single line... i cannot move it, i have to unlock the window, drag it up for it to be reset.

**Comment by zuiji** [comment]
I got the same problem on my alt but my main work alright but left channel only filling half of the box

**Comment by zuiji** [comment]
And but playing on lightshope.org

**Comment by shagu** [comment]
Please reset the first-run wizard in the pfUI option menu and select "Use Defaults" on next reload.

**Comment by zuiji** [comment]
Did try that do not help me

**Comment by pawelkw** [comment]
Doesn't fix it for me either.

**Comment by sippycupmcjr** [comment]
I'm also running into this issue (I downloaded pfUI today), and in my experience it's caused by both pet actions and receiving quest credit.

Overview of the problem and reproducing the bug: https://youtu.be/T-BRsNFB5w8
New character, running default options, everything except pfUI disabled: https://youtu.be/-_VywKOrxeE

Summary of the videos: The chat on the left part of the screen snaps to a much smaller size when you receive credit for a quest (looting a quest item or killing something, not sure about about interacting with objects). The bug also occurs when changing a (warlock's) pet's attack/movement/follow settings.
The second video is basically reproducing the bug on a level 1 character that had not been logged into since installing pfUI (and all addons are disabled in the video). However, I noticed that bug also happens for no particular reason in the second video (may be related to opening the quest log).

**Comment by shagu** [comment]
Thanks for the detailled report. Might be related to the missing combatlog?

**Comment by sippycupmcjr** [comment]
May have found the issue - I had simple chat enabled and when I disabled it it seems like the problem went away. I really should have checked that first.

**Comment by Lichery** [comment]
yes, this bug is due to simple chat enabled
