### ISSUE TITLE
Thirdparty.lua error.

### ISSUE THREAD

**Issue by Vartis** [shagu/pfUI#734]
After updating pfui i have started to get this error at random times during raid. 

> Interface\Addons\pFUI\modules\thirdparty.lua:652: attempt to concatenate field 'label' (a nil value)
Chat image : https://i.imgur.com/CjeozJw.png

With these thirdparty addons checked. : https://i.imgur.com/spHd18l.png

It has been hard to test exactly what is causing the issue as it has happened exclusively in raid for me.

**Comment by Road-block** [comment]
Make sure all your font options are set.  
If worse comes to worse execute the "first run" wizard.

**Comment by Vartis** [comment]
I ran the first run wizard and still got the error. Disabling all thirdparty dpsmate options seems to have fixed it. I'm not sure what you mean by font options.

**Comment by shagu** [comment]
Which version of DPSMate are you running?

**Comment by Vartis** [comment]
I am using b126 however I will be updating to the new version soon.  Since disabling all third party options I haven't seen the error. Its very difficult to test the issue with it happening exclusively in an active raid.

**Comment by shagu** [comment]
> Interface\Addons\pFUI\modules\thirdparty.lua:652: attempt to concatenate field 'label' (a nil value)

please make sure, your folder is called `pfUI` and not `pFUI`. And please try again with the latest version of pfUI.

**Comment by Road-block** [comment]
Had the same error, my folder is named properly. 
`[2017/11/16 22:52:10-3564-x96]: modules\thirdparty.lua:652: attempt to concatenate field `label' (a nil value)
modules\thirdparty.lua:652: in function <Interface\AddOns\pfUI\modules\thirdparty.lua:651>`
Happened after I /focus [Zealot Lor'Khan](http://db.vanillagaming.org/?npc=11347) when he died.

`[2017/11/16 22:52:25-3564-x33]: modules\thirdparty.lua:652: attempt to concatenate field `label' (a nil value)
modules\thirdparty.lua:652: in function <Interface\AddOns\pfUI\modules\thirdparty.lua:651>
<in C code>: in function `TurnOrActionStop'
<string>:"TURNORACTION":5: in main chunk`

`[2017/11/16 22:52:53-3564-x21]: modules\thirdparty.lua:652: attempt to concatenate field `label' (a nil value)
modules\thirdparty.lua:652: in function <Interface\AddOns\pfUI\modules\thirdparty.lua:651>
<in C code>: in function `TargetByName'
modules\nameplates.lua:56: in function <Interface\AddOns\pfUI\modules\nameplates.lua:14>`

`[2017/11/16 22:52:53-3564-x21]: modules\thirdparty.lua:652: attempt to concatenate field `label' (a nil value)
modules\thirdparty.lua:652: in function <Interface\AddOns\pfUI\modules\thirdparty.lua:651>
<in C code>: in function `ClearTarget'
modules\nameplates.lua:68: in function <Interface\AddOns\pfUI\modules\nameplates.lua:14>`

and many more like that.

**Comment by Road-block** [comment]
Just had an idea .. is it possible HealComm catches the resurrection spell these NPCs cast as part of the encounter and pfUI tries to get a valid unitid for the focused unit?

**Comment by Road-block** [comment]
So I know what's happening here but not sure who's fault it is.  
As part of the High Priest Thekal encounter in ZG the 3 NPCs start a Resurrection cast when either of them dies.  
 - HealComm somehow catches that and sends a `HealComm_Ressupdate` event.  
 - pfUI responds to that event by doing a scan of all units in its `pfUI.uf.frames` cache (including focus)
 - error happens because the focus unit does not have a valid `base.label`

Now for the blame game.  
 - HealComm initiates resurrection only through `SPELLCAST_START` which should be a player only event and `CHAT_MSG_ADDON` received from another player.  
   - Is the server bugged and firing SPELLCAST_START for npcs?
   - Is HealComm somehow sending a `CHAT_MSG_ADDON` with bad data?
 - pfUI should in any case probably blacklist the focus frame that doesn't correspond to a real unitid from some operations. Or maybe check if the source or target of the event is a player and not an npc.
 
The relevant combatlog messages are.  
`High Priest Thekal begins to cast Resurrection.`  
`Zealot Zath begins to cast Resurrection.`  
`Zealot Lor'Khan begins to cast Resurrection.`  

@Aviana

**Comment by Vartis** [comment]
I can confirm that it only happens in ZG.

**Comment by shagu** [comment]
Can you please verify this with the latest version and quote me the exact error message you got?

**Comment by Vartis** [comment]
After using the newest version of pfui this error has stopped happening. In the 40 days since my last post and 6+ zg runs completed I haven't seen the error anymore.
