### ISSUE TITLE
offscreen split bank/ no screenshots allowed

### ISSUE THREAD

**Issue by ldrancer** [shagu/pfUI#774]
When you try to split stacks in the bank using the bagmod, and the item is on the left side, enough, it opens the split dialog box, half offscreen, and you cant split without changing spots in the bank.  another bug i just discovered, i dont know if this is a bug or not, i just tried to take a screenshot of this, and it wouldnt let me screenshot it, but , it wont let me screenshot with the stack split dialog box openned up.  i have the bank open, it lets me hit printscreen and grabs.  it ends upcopying my desktop and missing the game maximized screen.
https://s8.postimg.org/i5r8evwdh/Wo_WScrn_Shot_112917_154422.jpg
this is the picture i took before i tried to split the Large Brilliant Shards on the left side
![wowscrnshot_112917_154422](https://user-images.githubusercontent.com/31392163/33398281-6fb4b74e-d51c-11e7-89c6-4edec4cde592.jpg)

**Comment by Road-block** [comment]
The second part is expected as the split-stack frame is keyboard enabled, which means all keys are "eaten".  
So no screenshots but on the upside, you can still use the split frame with arrow keys + Enter and it will pickup however many items you had split.  
On-topic I've mentioned that problem few months ago, should probably do a pull request for it, the fix is trivial.  
```lua
StackSplitFrame:SetClampedToScreen(true)
```

You can temporarily do `/run StackSplitFrame:SetClampedToScreen(true)` in your chat when you login for now till it's fixed.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/03d4d530fdca95d41b31499ebc1600fdfe52314b
