### ISSUE TITLE
readme: add description of module features

### ISSUE THREAD

**Issue by Cephel** [shagu/pfUI#781]
Hi, I'd like to just have a list somewhere of common addons that pfUI replaces or atleast provides an alternative. Not every functionality is obvious at first and the component names aren't very descriptive right now.

I want to improve my UI loading times and disabling addons that deal with the same functionality is a good start.

**Comment by stokbaek** [comment]
Take a look in [modules folder](https://github.com/shagu/pfUI/tree/master/modules), that is the best option. It is impossible to know or research what the most common addon does.

A module could for example replace bags this does not mean that it does the same as Bagon or Engbags. For some people will the features that pfUI bags brings be enough, but some others wont it be enough. For this reason is it impossible to make a list as it is personal preference which addons pfUI can replace.
