### ISSUE TITLE
KTM and DPSMate UI Scale and pfUI

### ISSUE THREAD

**Issue by Rustedbucket** [shagu/pfUI#874]
Good afternoon!

Loving the UI, Shag, thanks!

I'm curious, though, every time I reopen the game, I'm forced to reset the scale of both of my _docked_ KTM and DPSMate UI settings.  Is there a way to set the scale on each of these and have them NOT reset every log out?

Thanks!

**Comment by shagu** [comment]
Hi,

KTM gets a scale, because KTM doesn't support setting the width directly to match the chat frame. Regarding DPSMate, I have no idea what causes the Scale reset. Do you have the skin option set?

Also I would be highly interested what is wrong with the skin/dock settings that you need to change that each time. Could you please provide a screenshot on what you would like to achieve?
