### ISSUE TITLE
Chat bug

### ISSUE THREAD

**Issue by Lichery** [shagu/pfUI#892]
after changing the chat settings, this bug appears:
![bandicam 2018-04-22 21-38-23-983](https://user-images.githubusercontent.com/24303693/39098584-adc153b0-4675-11e8-8375-c154885b636b.jpg)
for example:
enable/disable "Enable Timestamps", "Show Items On Mouseover" and others

**Comment by Lichery** [comment]
after reset config this bug disappears

**Comment by shagu** [comment]
Works for me.

**Comment by Lichery** [comment]
deleted folder 1, test on retrowow, enabled only pfUI. I chose the default settings. In the beginning, everything is fine. Something I change in chat settings, I do a reload and all messages in the left chat are written from the middle

**Comment by Lichery** [comment]
first run game after delete WTF:
before click "Use Defaults":
![bandicam 2018-04-22 21-55-15-814](https://user-images.githubusercontent.com/24303693/39098755-ffd8643e-4677-11e8-859d-a0d3b9398bc7.jpg)
after:
![bandicam 2018-04-22 21-55-19-546](https://user-images.githubusercontent.com/24303693/39098756-06e7b298-4678-11e8-847d-f48206f27cab.jpg)

**Comment by Lichery** [comment]
same thing after changing the chat settings, I change anything and the chat also shifts to the middle

**Comment by shagu** [comment]
*Regarding the firstrun wizard:*
You see the text in the middle because pfUI doesn't touch the chat windows, till you click "Use Defaults" or select the corresponding action in the firstrun wizard, to let pfUI handle the chat positions. 

I'm still not able to reproduce it. It doesn't matter how much I change in the chat-settings, my chat keeps in the correct position.

**Comment by Lichery** [comment]
very strange ... I do not understand what is happening. Restarted again and everything works as it should ...
