### ISSUE TITLE
Chat does not fill full left chat window - cuts off randomly.

### ISSUE THREAD

**Issue by USERNAMETAKENN** [shagu/pfUI#897]
The chat window does not properly fill the left chat window

![pfui](https://user-images.githubusercontent.com/38762309/39316844-6358f070-4937-11e8-8b00-8f9ec30f3c52.jpg)

Chat cuts off. I can fix it temporarily by clicking the "left" directional button at the bottom left of the UI.

![pfui2](https://user-images.githubusercontent.com/38762309/39317258-6257f7ec-4938-11e8-92af-f0de02ae0521.jpg)

But as I said it's just temporary. After about a couple minutes of play it seems like the change cache resets back to a default and the problem persists.
![pfui3](https://user-images.githubusercontent.com/38762309/39317504-f3a0ab68-4938-11e8-8696-1762f259f0cd.jpg)

I saw a post here saying it happens because "Simple chat" is enabled, but I don't see any "simple chat" option anywhere. Any clues?

**Comment by shagu** [comment]
Did you ran the firstrun dialog? ('Use Daefaults')

**Comment by USERNAMETAKENN** [comment]
I'm unfamiliar with the runfirst dialog use defaults - I would assume that would reset all my PFUI to factory forcing me to re-set up everything.

Where is that option, and what does it do?

**Comment by Lichery** [comment]
and as I described in my issue, it also appeared after reload UI or chat settings. But unfortunately I still did not understand what caused it.

**Comment by Lichery** [comment]
if you need help, I'm ready to test, post debug messages to the chat to catch this bug, but I need data that specifically needs to be displayed.

P.S. unfortunately I am leaving for the May holidays to the dacha and I will not be until 1 May.

**Comment by Lichery** [comment]
https://youtu.be/z7AkVLxoZVM

**Comment by shagu** [comment]
@Lichery Thanks! I'll check it later this evening. Did you only saw this on retro-wow or is it independent of any server?

**Comment by Lichery** [comment]
@shagu same thing on my personal server mangos classic. I will check later on other servers, but I do not think that the problem is in the server

**Comment by Lichery** [comment]
Kronos I same bug

**Comment by Herpaderpp** [comment]
Same issue here on nefarian.

**Comment by yw-1111** [comment]
@Artur91425 @Herpaderpp @USERNAMETAKENN 
I had the exact same issue, and i think i maybe have fixed the problem, try this:
1. at interfact option -> advanced options -> chat -> simple chat: make sure this is unchecked
2. try disable pfUI (find pfUi -> Components -> Disable Module Chat), so you can see your regular chat box, try to adjust the height of the regular chat box height to match your pfUI chat height.

I think this chat random height problem only happens when there is a changing in zone, meaning the system try to reload the regular chatbox with local zone channel, and pfUI does not keep refreshing the setting. Or maybe is the simple chat setting keep the chat under wow control. Either way, try this and see if it can resolve you issue.

**Comment by yw-1111** [comment]
Actually updo testing it again, just disable the simple chat option should do it. :)

**Comment by shagu** [comment]
> Why is my chat always resetting to only 3 lines of text?
You need to disable the "Simple Chat" in blizzards interface settings (Advanced Options). Then relog and reset/run the firstrun wizard again.

- FAQ (https://github.com/shagu/pfUI)
