### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Lichery** [shagu/pfUI#910]
![bandicam 2018-05-07 20-03-04-124](https://user-images.githubusercontent.com/24303693/39714091-ae9b9972-5231-11e8-856e-cb709b88e0bd.jpg)
When mouseover with Shift on debuff 'Weakened Soul'

**Comment by Road-block** [comment]
The underlying problem is with filtering (`"HELPFUL"` filter missing somewhere), this shouldn't run for **De**buffs, only for Buffs afaik.  
But you should either disable the "single line errors" from pfUI or get an error reporting addon so you can post the full error message with the call stack.  
*line 59 is the GetUnitColor method which is called in a bunch of places, a proper error callstack would show which of the calls ends up with the error*  
`unit` argument somehow ends up being `nil` but it's hard to know how that happens without the full callstack.

**Comment by Lichery** [comment]
BugSack is better addon)
![bandicam 2018-05-08 22-02-26-007](https://user-images.githubusercontent.com/24303693/39777206-9d04bde4-530b-11e8-8dac-91b2d365ce0f.jpg)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/8d8869386f38a83f9d54f59626307ea19eed24c3
