### ISSUE TITLE
Transfer settings from elvUI

### ISSUE THREAD

**Issue by gamer4eg** [shagu/pfUI#956]
The meaning of this function is obvious, many players have already configured the interface in the elvUI backport. And ordinary users (rather than nerds like us) find setting up such an interface time-consuming.

https://github.com/ElvUI-TBC/ElvUI

**Comment by shagu** [comment]
Hi, thanks for your suggestion. But pfUI and ElvUI are very different in its core and it would be hell of a work to map all possible settings of ElvUI to the pfUI counterpart, also some exist, others don't. I'm not interested in ElvUI at all, so I don't see myself spending weeks of work and reading through the entire ElvUI code. Also, I know too less about ElvUI to make this happen in a proper way and rather continue to work on the actual pfUI instead of this one.

I'm closing this as "Won't fix".

If you really want and need that, you would need to do it yourself. If so, I suggest to do it as an external Addon, maybe a pfUI extension module or a simple script, such as others made Questie into pfQuest imports/converters.

**Comment by gamer4eg** [comment]
At least the location and size of the panels ...
