### ISSUE TITLE
Target frame not visible

### ISSUE THREAD

**Issue by Omnipotence** [shagu/pfUI#976]
At very specific circumstances the target frame is not visible. This happens when I'm playing on my warlock. When I aggro a mob, but my pet attacks it before the mob can attack my character, the target frame does not become visible. Clearing the target via escape and retargeting does not make the target frame appear either. I can still attack and cast spells while this happens.

**Comment by shagu** [comment]
Which version of the game is that and on which server? Do you have any other addons running and did you verified that this does not happen without pfUI?

**Comment by Omnipotence** [comment]
I've tested some more. I'm playing on the Vanilla+ server, version 1.12.1 and the latest version of the addon. It only occurs when both pfUI and TourGuideVanilla (https://github.com/cralor/TourGuideVanilla) are enabled. When either of the two is disabled the target frame will be visible.

**Comment by shagu** [comment]
Since they require you to use a custom client, it can be everything. The addon relies a lot on game version to detect vanilla or tbc mode, game textures to identify rangescannners, talents to identify durations and other game mechanics and much more. That's all not reliable on a custom client and I'm sorry but I can't help you on that, as long as it does not happen on a real 1.12 client/server. Good luck though
