### ISSUE TITLE
[UnitFrames-General] hide powerbar for non-mana users

### ISSUE THREAD

**Issue by shikulja** [shagu/pfUI#980]
Such an option was in LunaUF. 
It’s very convenient, it’s like a healer in a raid, it relieves me of unnecessary information

**Comment by shagu** [comment]
To be honest, I don't see why hunter's mana would be more important than the rage of the tanks.
Also due to how the unitframe sizes are calculated, the power bar is a crucial part and would require quite some modifications to not fall into any regressions on thirdparty modules and other settings. I don't see myself doing it for the above reasons. If anyone feels like doing it and have it tested properly, I will merge it but I'm not going to put any time into it.

**Comment by shikulja** [comment]
Raid leaders monitor mana before pulling the boss. If do not take into account the fury of tanks.
This is important for me, since healer, and I'm only interested in the mana of the players, and for the rest it is better to have a larger health bar, without distracting streaks of rage.
It is a pity that it is difficult to implement.

**Comment by shagu** [comment]
You can still go into the raid settings, uncheck "Inherit Default Colors" and set the Focus, Rage and Energy color to something transparent.

**Comment by shikulja** [comment]
@shagu thanks, maybe I'll try to do so
