### ISSUE TITLE
TBC Clique

### ISSUE THREAD

**Issue by GioBego** [shagu/pfUI#985]
pfUI is not working with Clique in TBC ... compatible Clique and/or patch are just for Vanilla

**Comment by shagu** [comment]
That's right. I did an example for Clique on vanilla while there was no builtin click-casting in pfUI.

I don't plan to fork Clique-TBC, write a plugin for it, and maintain it. Especially not since I've been quite happy with the already built-in click casting of pfUI. You'd need to find someone else who's willing to update Clique if you want it.
