### ISSUE TITLE
Ability Icon Will Not Update

### ISSUE THREAD

**Issue by nonameform** [shagu/pfUI#992]
As a Druid I am using Prowl all the time and after the last update I have noticed that the icon will not update when I enter or exit stealth. It either stays in [original form](https://wow.zamimg.com/images/wow/icons/large/ability_ambush.jpg) or in [activated form](https://wow.zamimg.com/images/wow/icons/large/spell_nature_invisibilty.jpg). The cooldown timer works as before no matter the icon.

Also UI will not always display Rake debuff on target even though it adds a combo point (i.e. not misses). Might be a regression linked to one of the latest commits.

P.S. Is it possible to do something about nameplates? When a target is moving, nameplate jiggles quite a lot compared to the original Blizzard UI and it gets especially bad when fighting multiple targets or using a ship with an opposing faction character on it.

**Comment by shagu** [comment]
> Also UI will not always display Rake debuff on target even though it adds a combo point (i.e. not misses). Might be a regression linked to one of the latest commits.

I haven't changed anything there for quite a while. Also if it's just sometimes, it could also be a server hickup where a combat log message gets lost. The entire debuff estimation is based on pure guessing based on combat log entries.

> P.S. Is it possible to do something about nameplates? When a target is moving, nameplate jiggles quite a lot compared to the original Blizzard UI and it gets especially bad when fighting multiple targets or using a ship with an opposing faction character on it.

Not really, there isn't much that can be done on nameplates from the addon side in Vanilla and TBC. Nameplates are drawn and positioned by the native c-part of the client. The only option we have, is to place a lua-created frame on-top of the client-drawn object. Whenever the client moves it's original object, it also has to realign the lua-created one to it. This process can (depending on the system, drivers, video-mode, graphic card, etc) cause wobbly effects since the native one is updated faster. I can't control the clockrate at which the lua-frame is realigned.

> As a Druid I am using Prowl all the time and after the last update I have noticed that the icon will not update when I enter or exit stealth. It either stays in original form or in activated form. The cooldown timer works as before no matter the icon.

Thanks for your report, I've been able to reproduce it and will provide a fix today.

**Comment by shagu** [comment]
Fixed: https://github.com/shagu/pfUI/commit/f9dec834dc8645a55524dd20310d9304433fc466
