### ISSUE TITLE
pfUI failed to load on 1.13.5

### ISSUE THREAD

**Issue by PedanIhor** [shagu/pfUI#993]
pfUI is unavailable to use on the official World of Warcraft Classic

**Comment by shikulja** [comment]
> pfUI is unavailable to use on the official World of Warcraft Classic

the first page says:
`An AddOn for World of Warcraft: Vanilla (1.12.1) and The Burning Crusade (2.4.3)`

**Comment by shagu** [comment]
See the FAQ: https://github.com/shagu/pfUI#faq

> Will there be pfUI for Activision's "Classic" remakes?
No, it would require an entire rewrite of the AddOn since the game is now a different one. The AddOn-API has evolved during the last 15 years and the new "Classic" versions are based on a current retail gameclient. I don't plan to play any of those new versions, so I won't be porting any of my addons to it.
